export const EXPERIENCE = `
query{
    career{
      data{
        attributes{
          ExperienceTitle{
            Title
            SubTitle
          }
          experiences{
            data{
              id
              attributes{
                Experience{
                  id
                  Title
                  Body
                  Images{
                    data{
                      attributes{
                        url
                        alternativeText
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }`;
