export const SITEMAP = `
query{
  sitemap{
    data{
      id
      attributes{
        PageTitle
        Slug
        ServicesImage{
          id
          LinkIcons{
            id
            href
            label
          }
          Icons
          {
            data{
              id
              attributes{
                url
                alternativeText
              }
            }
          }
          HoverIcon{
            data{
              id
              attributes{
                url
                alternativeText
              }
            }
          }
        }
        StrapiServices{
          id
          LinkIcons{
            id
            href
            label
          }
          Icons{
            data{
              id
              attributes{
                url
                alternativeText
              }
            }
          }
        }
        StrapiChild{
          id
          href
          label
        }
        CompanyTitle
        CompanyLinks{
          id
          Class
          Links{
            id
            href
            label
          }
        }
        InsightsTitle
        InsightsLinks{
          id
          Class
          Links{
            id
            href
            label
          }
        }
        OtherLinks{
          id
          Class
          Links{
            id
            href
            label
          }
        }
        HomeLinks{
          id
          href
          label
        }
       	SolutionTitle
        SolutionLinks{
          id
          Links{
            id
            href
            label
          }
          Class
        }
      }
    }
  }
}
`;
