export const FOOTER = `
query{
    footers{
      data{
        id
        attributes{
          FooterTitle
          FooterImg{
            data{
              id
              attributes{
                url
                alternativeText
              }
            }
          }
          SocialIcons{
            id
            LinkIcons{
              id
              href
              label
            }
            Icons{
              data{
                id
                attributes{
                  alternativeText
                  url
                }
              }
            }
            HoverIcon{
              data{
                id
                attributes{
                  alternativeText
                  url
                }
              }
            }
          }
        	locations{
          data{
            id
            attributes{
              AddressLocation{
                Title
                Description
                Body
              }
              contact_infos{
                data{
                  id
                  attributes{
                    ContactInfo{
                      id
                      LinkIcons{
                        href
                        label
                      }
                      Icons{
                        data{
                          id
                          attributes{
                            alternativeText
                            url
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
          CompanyTitle
          Company{
            id
            LinkIcons{
              href
              label
            }
            Icons{
              data{
                id
                attributes{
                  url
                  alternativeText
                }
              }
            }
            HoverIcon{
              data{
                id
                attributes{
                  url
                  alternativeText
                }
              }
            }
          }
          ServiceTitle
          Services{
            id
            LinkIcons{
              href
              label
            }
            Icons{
              data{
                id
                attributes{
                  url
                  alternativeText
                }
              }
            }
            HoverIcon{
              data{
                id
                attributes{
                  url
                  alternativeText
                }
              }
            }
          }
          CopyTitle
          Copy{
            id
            href
            label
          }
           UsaAddress
        }
      }
    }
  }

  `;

export const NOTFOUND = `query{
  pageNotFound{
    data{
      id
      attributes{
        PageTitle
        Slug
        Description{
          id
          Title
          SubTitle
          Description
          Body
          Images{
            data{
              id
              attributes{
                alternativeText
                url
              }
            }
          }
        }
        GoBackLink{
          id
          href
          label
        }
      }
    }
  }
}`;
export const HEADER = `
query{
  headers{
    data{
      id
      attributes{
        SolutionTitle
        SolutionDesc
        SolutionComponents{
          id
          Title
          Description
          Images{
            data{
              id
              attributes{
                name
                alternativeText
                url
              }
            }
          }
          Icons{
            data{
              id
              attributes{
                name
                alternativeText
                url
              }
            }
          }
          Links{
            id
            href
            label
          }
        }
       	 Logo{
          data{
            id
            attributes{
              alternativeText
              url
            }
          }
        }
         MobImage{
          data{
            attributes{
              alternativeText
              url
            }
          }
        }
     	   MobileView{
          id
          Title
          SubTitle
          Body
          Description
          Images{
            data{
              attributes{
                alternativeText
                url
              }
            }
          }
        }
        ServiceTitle
     	   Services{
          id
          Description
          Link{
            id
            href
            label
          }
          Image{
            data{
              id
              attributes{
                alternativeText
                url
              }
            }
          }
        }
        CompanyTitle
        Company{
          id
          Title
          Description
          Image{
            data{
              id
              attributes{
                url
                alternativeText
              }
            }
          }
          Link{
            id
            href
            label
          }
        }
        CompanyDetails{
          id
          Detail{
            id
            Title
            Description
          }
          Link{
            id
            href
            label
          }
          ClassIcon
           Hiring
        }
       	InsightTitle
        Insights{
          id
          Title
          Description
          Image{
            data{
              id
              attributes{
                alternativeText
                url
              }
            }
          }
          Link{
            id
            href
            label
          }
        }
        InsightsDetail{
          id
          Detail{
            id
            Title
            Description
          }
          Link{
            id
            href
            label
          }
          ClassIcon

        }
        contact_form_title{
          data{
            id
            attributes{
              Right{
                  id
                  Title
                  Description
              }
            }
          }
        }
         LatestBlogs
        blogs{
          data{
            id
            attributes{
              Blogs{
                id
                tagLabel
                Title
                HeaderImage{
                  data{
                    id
                    attributes{
                      url
                      alternativeText
                    }
                  }
                }
                image{
                  data{
                    id
                    attributes{
                      url
                      alternativeText
                    }
                  }
                }
                Links{
                  id
                  href
                  label
                }
              }
            }
          }
        }
      }

    }
  }
}
`;
